# Generated by Django 2.2.5 on 2019-09-25 16:01

import calls.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text='The subscriber phone number that originated the call', max_length=11, validators=[calls.validators.validate_phone_number])),
                ('destination', models.CharField(help_text='The phone number receiving the call', max_length=11, validators=[calls.validators.validate_phone_number])),
            ],
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('start', '1 - Start'), ('end', '2 - End')], help_text="Indicate if it's a call 'start' or 'end' record", max_length=5)),
                ('timestamp', models.DateTimeField(help_text='The timestamp of when the event occurred')),
                ('call_id', models.ForeignKey(help_text='Unique for each call record pair', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='calls.Call')),
            ],
            options={
                'unique_together': {('type', 'call_id')},
            },
        ),
        migrations.CreateModel(
            name='CallInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_end', models.DateField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('call_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='calls.Call')),
            ],
            options={
                'unique_together': {('call_id',)},
            },
        ),
    ]
